/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author PC
 */
import forms.LocationForm;
import forms.SearchByVille;
import forms.ProprietaireForm;
import forms.BienForm;
import javax.swing.table.DefaultTableModel;
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
    initComponents();
    
    this.setTitle("Gestion Agence Immobilière");
    this.setLocationRelativeTo(null);
    this.setExtendedState(MAXIMIZED_BOTH);

    this.setContentPane(desktopPane); 
    
    
 
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        bienMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        villeMenuItem = new javax.swing.JMenuItem();
        typesMenuItem = new javax.swing.JMenuItem();
        menuStat = new javax.swing.JMenu();
        menuLoyersVille = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(153, 102, 0));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        bienMenuItem.setMnemonic('o');
        bienMenuItem.setText("Bien");
        bienMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bienMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(bienMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Proprietaire");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Location");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("se déconnecter");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Recherche");
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        villeMenuItem.setMnemonic('t');
        villeMenuItem.setText("Par ville de bien");
        villeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villeMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(villeMenuItem);

        typesMenuItem.setMnemonic('y');
        typesMenuItem.setText("Par type de bien");
        typesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typesMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(typesMenuItem);

        menuBar.add(editMenu);

        menuStat.setMnemonic('h');
        menuStat.setText("Statistiques");
        menuStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStatActionPerformed(evt);
            }
        });

        menuLoyersVille.setMnemonic('c');
        menuLoyersVille.setText("Loyer par ville");
        menuLoyersVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoyersVilleActionPerformed(evt);
            }
        });
        menuStat.add(menuLoyersVille);

        menuBar.add(menuStat);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void bienMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bienMenuItemActionPerformed
        // TODO add your handling code here:
       
        System.out.println("BIEN CLIQUE");
    for (javax.swing.JInternalFrame f : desktopPane.getAllFrames()) {
        if (f instanceof BienForm) {
            f.toFront(); 
            try {
                f.setSelected(true); 
            } catch (java.beans.PropertyVetoException ex) {
                ex.printStackTrace();
            }
            return; 
        }
    }

    
    BienForm form = new BienForm();
    desktopPane.add(form);

    
    form.setSize(800, 600);          
    form.setLocation(50, 50);        

    form.setVisible(true);          

    try {
        form.setSelected(true);      
    } catch (java.beans.PropertyVetoException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_bienMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
     
for (javax.swing.JInternalFrame f : desktopPane.getAllFrames()) {
    if (f instanceof ProprietaireForm) {
        f.toFront();
        try {
            f.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
        return;
    }
}


ProprietaireForm pf = new ProprietaireForm();
desktopPane.add(pf);


pf.setSize(700, 500);
pf.setLocation(60, 60);

pf.setVisible(true);

try {
    pf.setSelected(true);
} catch (java.beans.PropertyVetoException ex) {
    ex.printStackTrace();
}
        
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void villeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villeMenuItemActionPerformed
        // TODO add your handling code here:
        
  
   System.out.println("CLICK OK");

    try {
        
        for (javax.swing.JInternalFrame f : desktopPane.getAllFrames()) {
            if (f instanceof SearchByVille) {
                f.toFront();
                f.setSelected(true);
                return;
            }
        }

        
        SearchByVille sv = new SearchByVille();

        
        desktopPane.add(sv);

        
        sv.setVisible(true);

       
        sv.setSelected(true);

        
        desktopPane.repaint();

    } catch (Exception e) {
        e.printStackTrace();
    }

   
    
    }//GEN-LAST:event_villeMenuItemActionPerformed

    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMenuActionPerformed

    private void typesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typesMenuItemActionPerformed
        // TODO add your handling code here:
        
        System.out.println("CLICK OK"); 

    try {
        
        for (javax.swing.JInternalFrame f : desktopPane.getAllFrames()) {
            if (f instanceof SearchByType) {
                f.toFront();
                f.setSelected(true);
                return;
            }
        }

        
        SearchByType st = new SearchByType();

        
        desktopPane.add(st);

        
        st.setVisible(true);

       
        st.setSelected(true);

        
        desktopPane.repaint();

    } catch (Exception e) {
        e.printStackTrace();
    } 
        
        
        
        
    }//GEN-LAST:event_typesMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
        
        System.out.println("LOCATION CLIQUE");

    try {
        
        for (javax.swing.JInternalFrame f : desktopPane.getAllFrames()) {
            if (f instanceof LocationForm) {
                f.toFront();
                f.setSelected(true);
                return;
            }
        }

        
        LocationForm lf = new LocationForm();

        
        desktopPane.add(lf);

       
        lf.setSize(900, 600);
        lf.setLocation(30, 30);

    
        lf.setVisible(true);

        
        lf.setSelected(true);

        desktopPane.repaint();

    } catch (Exception e) {
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void menuStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuStatActionPerformed

    private void menuLoyersVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoyersVilleActionPerformed
        // TODO add your handling code here:
        
        System.out.println("GRAPHIQUE CLIQUE");

try {
    
    for (javax.swing.JInternalFrame f : desktopPane.getAllFrames()) {
        if (f instanceof GraphiqueForm) {
            f.toFront();
            f.setSelected(true);
            return;
        }
    }

    
    GraphiqueForm gf = new GraphiqueForm();

    
    desktopPane.add(gf);

    
    gf.setSize(900, 600);
    gf.setLocation(40, 40);

    
    gf.setVisible(true);

   
    gf.setSelected(true);

    desktopPane.repaint();

} catch (Exception e) {
    e.printStackTrace();
}
        
    }//GEN-LAST:event_menuLoyersVilleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bienMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuLoyersVille;
    private javax.swing.JMenu menuStat;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem typesMenuItem;
    private javax.swing.JMenuItem villeMenuItem;
    // End of variables declaration//GEN-END:variables

}
